routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['install']], function () {
    //Auth Route
    Route::get('/login', function () {
        return redirect('login');
    });

    Auth::routes();

    //Frontend Route
    Route::get('/', 'WebsiteController@index');
    Route::get('/post/{slug?}', 'WebsiteController@single');
    Route::get('/category/{id?}', 'WebsiteController@category_archive');
    Route::get('/notice/{id?}', 'WebsiteController@notice');
    Route::get('/event/{id?}', 'WebsiteController@event');
    Route::post('/contact/send_message', 'WebsiteController@send_message');
    Route::get('/site/{slug?}', 'WebsiteController@index');


    Route::group(['middleware' => ['auth']], function () {
        /** Common Route for All **/
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        //Profile Controller
        Route::get('profile/my_profile', 'ProfileController@my_profile');
        Route::get('profile/edit', 'ProfileController@edit');
        Route::post('profile/update', 'ProfileController@update');
        Route::get('profile/changepassword', 'ProfileController@change_password');
        Route::post('profile/updatepassword', 'ProfileController@update_password');


        /** Permission Route Group **/
        Route::group(['middleware' => ['permission']], function () {

            //User Controller
            Route::get('users/get_users/{user_type}', 'UserController@get_users');
            Route::resource('users', 'UserController');

            //FrontOffice Route
            Route::get('frontoffice/{page?}', 'FrontOfficeController@index')->name('frontoffice.main_screen');
            Route::resource('admission_enquiries', 'AdmissionEnquiryController');
            Route::resource('visitor_informations', 'VisitorInformationController');
            Route::resource('phone_call_logs', 'PhoneCallLogController');
            Route::resource('complains', 'ComplainController');

            //Teacher Route
            Route::get('teachers/excel_import', 'TeacherController@excel_import')->name('teachers.excel_import');
            Route::post('teachers/excel_store', 'TeacherController@excel_store')->name('teachers.excel_import');
            Route::resource('teachers', 'TeacherController');
            Route::post('teachers/active/{id}', 'TeacherController@active')->name('teachers.active');
            Route::post('teachers/deactivate/{id}', 'TeacherController@deactivate')->name('teachers.deactivate');
            Route::get('teachers/certificate/{id}', 'TeacherController@certificate_create');
            Route::post('teachers/certificate_store', 'TeacherController@certificate_store');
            Route::get('teachers/nid/{id}', 'TeacherController@nid_create');
            Route::post('teachers/nid_store', 'TeacherController@nid_store');
            Route::get('teachers/certificate/view/{id}', 'TeacherController@certificate_view');
            Route::post('teachers/certificate_update/{id}', 'TeacherController@certificate_update');
            Route::match(['get', 'post'], 'teachers/certificate_remark/{id}', 'TeacherController@certificate_remark');

            //Parents Route
            Route::get('parents/get_parents', 'ParentController@get_parents');
            Route::get('parents/get_parents_list/{class_id}/{section_id}', 'ParentController@get_parents_list');
            Route::resource('parents', 'ParentController');
            Route::get('parents/nid/{id}', 'ParentController@nid_create');
            Route::post('parents/nid_store', 'ParentController@nid_store');

            //Student Route
            Route::get('students/excel_import', 'StudentController@excel_import')->name('students.excel_import');
            Route::post('students/excel_store', 'StudentController@excel_store')->name('students.excel_store');
            Route::get('students/id_card/{student_id}', 'StudentController@id_card')->name('students.view_id_card');
            Route::get('students/class/{class_id?}', 'StudentController@class')->name('students.index');
            Route::get('students/get_subjects/{class_id}', 'StudentController@get_subjects');
            Route::get('students/get_students/{class_id}/{section_id}', 'StudentController@get_students');
            Route::match(['get', 'post'], 'students/promote/{step?}', 'StudentController@promote')->name('students.promote');
            Route::resource('students', 'StudentController');
            Route::post('students/active/{id}', 'StudentController@active')->name('students.active');
            Route::post('students/deactivate/{id}', 'StudentController@deactivate')->name('students.deactivate');
            Route::post('students/certificate_remove/{id}', 'StudentController@certificate_remove');
            Route::get('students/certificate/{id}', 'StudentController@certificate_create');
            Route::post('students/certificate_store', 'StudentController@certificate_store');

            //Class Controller
            Route::resource('class', 'ClassController');
            Route::post('classes/class', 'ClassController@get_class');


            //Section Route
            Route::post('sections/section', 'SectionController@get_section');
            Route::get('sections/class/{class_id}', 'SectionController@index')->name('sections.index');
            Route::resource('sections', 'SectionController');

            //Subject Route
            Route::get('subjects/class/{class_id}', 'SubjectController@index')->name('subjects.index');
            Route::post('subjects/subject', 'SubjectController@get_subject');
            Route::resource('subjects', 'SubjectController');

            //Assign Subject Route
            Route::post('assignsubjects/search', 'AssignSubjectController@search')->name('assignsubjects.index');
            Route::resource('assignsubjects', 'AssignSubjectController');

            Route::resource('syllabus', 'SyllabusController');
            Route::get('syllabus/class/{class_id?}', 'SyllabusController@class');
            Route::resource('assignments', 'AssignmentController');
            Route::get('assignments/class/{class_id}', 'AssignmentController@class');
            Route::resource('academic_years', 'AcademicYearController');
            Route::get('branch_list/{id}', 'AcademicYearController@branch_list')->name('branch_list');
            Route::resource('branches', 'BranchController');
            Route::resource('student_groups', 'StudentGroupController');

            //Class Routine
            Route::get('class_routines', 'ClassRoutineController@index')->name('class_routines.index');
            Route::get('class_routines/class/{class_id}', 'ClassRoutineController@class')->name('class_routines.index');
            Route::get('class_routines/manage/{class_id}/{section_id}', 'ClassRoutineController@manage')->name('class_routines.edit');
            Route::post('class_routines/store', 'ClassRoutineController@store')->name('class_routines.create');
            Route::get('class_routines/show/{class_id}/{section_id}', 'ClassRoutineController@show')->name('class_routines.index');

            //Attendance Controller
            Route::match(['get', 'post'], 'student/attendance', 'AttendanceController@student_attendance')->name('student_attendance.create');
            Route::post('student/attendance/save', 'AttendanceController@student_attendance_save')->name('student_attendance.create');
            Route::match(['get', 'post'], 'staff/attendance', 'AttendanceController@staff_attendance')->name('staff_attendance.create');
            Route::post('staff/attendance/save', 'AttendanceController@staff_attendance_save')->name('staff_attendance.create');


            //Utility Controller
            Route::match(['get', 'post'], 'administration/general_settings/{store?}', 'UtilityController@settings')->name('general_settings.update');
            Route::post('administration/theme_option/{store?}', 'UtilityController@update_theme_option')->name('theme_option.update');
            Route::get('administration/change_session/{session_id}', 'UtilityController@change_session')->name('general_settings.update');
            Route::get('administration/change_branch/{branch_id}', 'UtilityController@change_branch');
            Route::post('administration/upload_logo', 'UtilityController@upload_logo')->name('general_settings.update');
            Route::get('administration/backup_database', 'UtilityController@backup_database')->name('utility.backup_database');

            //Language Controller
            Route::resource('languages', 'LanguageController');

            //PickList Controller
            Route::get('picklists/type/{type}', 'PicklistController@type')->name('picklists.index');
            Route::resource('picklists', 'PicklistController');

            //Library Controller
            Route::get('librarymembers/librarycard/{id}', 'LibraryMemberController@library_card')->name('librarymembers.view_library_card');
            Route::post('librarymembers/section', 'LibraryMemberController@get_section');
            Route::post('librarymembers/student', 'LibraryMemberController@get_student');
            Route::resource('librarymembers', 'LibraryMemberController');

            //Book Controller
            Route::resource('books', 'BookController');

            //Book Issue  Controller
            Route::match(['get', 'post'], 'bookissues/list/{library_id?}', 'BookIssueController@index')->name('bookissues.index');
            Route::get('bookissues/return/{id}', 'BookIssueController@book_return')->name('bookissues.return');
            Route::resource('bookissues', 'BookIssueController');

            //BookCategory Controller
            Route::resource('bookcategories', 'BookCategoryController');

resources/views/backend/parents/modal/create.blade.php
<form action="{{route('parents.store')}}" class="ajax-submit" enctype="multipart/form-data" method="post"
      accept-charset="utf-8">
    @csrf
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">{{ ('Parent Name')}}</label>
            <input type="text" class="form-control" name="parent_name" value="{{ old('parent_name') }}" required>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ("Father's Name")}}</label>
            <input type="text" class="form-control" name="f_name" value="{{ old('f_name') }}" required>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ("Mother's Name")}}</label>
            <input type="text" class="form-control" name="m_name" value="{{ old('m_name') }}" required>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ("Father's Profession")}}</label>
            <input type="text" class="form-control" name="f_profession" value="{{ old('f_profession') }}">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ("Mother's Profession")}}</label>
            <input type="text" class="form-control" name="m_profession" value="{{ old('m_profession') }}">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ('Phone')}}</label>
            <input type="text" class="form-control" name="phone" value="{{ old('phone') }}">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ('Address')}}</label>
            <textarea class="form-control" name="address">{{ old('address') }}</textarea>
        </div>
    </div>


    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ('Email')}}</label>
            <input type="email" class="form-control" name="email" value="{{ old('email') }}" required>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">Parent NID Number</label>
            <input type="number" class="form-control" name="nid_number" value="{{ old('nid_number') }}" required>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">Parent NID</label>
            <input type="file" class="form-control nid_copy" name="nid_copy" value="" required>
            <p class="help-block oError" style="color: red;margin-bottom: 0"></p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ('Password')}}</label>
            <input type="password" class="form-control" name="password" required>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ('Confirm Password')}}</label>
            <input type="password" class="form-control" name="password_confirmation" required>
        </div>
    </div>

    <div class="col-md-12">
        <div class="form-group">
            <label class="control-label">{{ ('Profile Picture')}}</label>
            <input type="file" class="form-control dropify" name="image"
                   data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-info btn-block">Save Parent</button>
        </div>
    </div>
</form>
@section('js-script')
    <script type="text/javascript">

        $(document).ready(function () {
            var maxSize = '1024';
            var _validFileExtensions = [];
            var imgExtensions = [".jpg", ".jpeg", ".JPG", ".JPEG", ".png", "PNG"];
            var fileExtensions = [".jpg", ".jpeg", ".JPG", ".JPEG", ".png", "PNG", ".pdf", ".PDF"];

            function validateSingleInput(oInput) {
                if (oInput.type == "file") {
                    var sFileName = oInput.value;
                    if (sFileName.length > 0) {
                        if (oInput.className.match(/\bonlyImg\b/)) {
                            _validFileExtensions = imgExtensions;
                        } else {
                            _validFileExtensions = fileExtensions;
                        }
                        var blnValid = false;
                        for (var j = 0; j < _validFileExtensions.length; j++) {
                            var sCurExtension = _validFileExtensions[j];
                            if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                                blnValid = true;
                                break;
                            }
                        }
                        if (!blnValid) {
                            oInput.value = "";
                            return false;
                        }
                    }
                }
                return true;
            }

            function fileSizeValidate(fdata) {
                if (fdata.files && fdata.files[0]) {
                    var fsize = fdata.files[0].size / 1024;
                    if (fsize > maxSize) {
                        fdata.value = "";
                        return false;
                    } else {
                        return true;
                    }
                }
            }


            //                For teacher certificate

            $(document).on("change", ".nid_copy", function () {
                var noExtentionError = validateSingleInput(this);
                var noSizeError = fileSizeValidate(this);
                if (noExtentionError === false) {
                    $(this).siblings(".oError").show().text("The nid copy must be JPG, JPEG, PNG, PDF format.");
                    return false;
                } else {
                    $(this).siblings(".oError").hide();
                    if (noSizeError === false) {
                        $(this).siblings(".oError").show().text("The nid copy will be less than 1 MB. ");
                        return false;
                    } else {
                        $(this).siblings(".oError").hide();
                    }
                }
            });

        });

    </script>
@stop

resources/views/backend/parents/modal/parent-view.blade.php
<table class="table table-bordered">
	<tbody>
		<tr>
			<td style="text-align: center;" colspan="4"><img class="profile" src="{{ asset('public/uploads/images/'.$parent->image) }}"></td>
		</tr>
		<tr>
			<td>{{ ("Guardian's Name ") }}</td>
			<td>{{ $parent->parent_name }}</td>
		</tr>
		<tr>
			<td>{{ ("Student's Name ") }}</td>
			<td><a href="{{ route('students.show',$parent->student_id) }}">{{ $parent->first_name .' '.$parent->last_name }}</a></td>
		</tr>
		<tr>
			<td>{{ ("Father's Name ") }}</td>
			<td>{{ $parent->f_name  }}</td>
		</tr>
		<tr>
			<td>{{ ("Mother's Name ") }}</td>
			<td>{{ $parent->m_name }}</td>
		</tr>
		<tr>
			<td>{{ ("Father's Profession ") }}</td>
			<td>{{ $parent->f_profession }}</td>
		</tr>
		<tr>
			<td>{{ ("Mother's Profession ") }}</td>
			<td>{{ $parent->m_profession }}</td>
		</tr>
		<tr>
			<td>{{ ('Phone') }}</td>
			<td>{{ $parent->phone }}</td>
		</tr>
		<tr>
			<td>{{ ('Email') }}</td>
			<td>{{ $parent->email }}</td>
		</tr>
		<tr>
			<td>{{ ('Address') }}</td>
			<td>{{ $parent->address }}</td>
		</tr>
	</tbody>
</table>