routes/web.php
            //Student Payments
            Route::get('student_payments/create/{invoice_id?}', 'StudentPaymentController@create')->name('student_payments.create');
            Route::get('student_payments/class/{class_id}', 'StudentPaymentController@index')->name('student_payments.index');
            Route::resource('student_payments', 'StudentPaymentController');

            //Message Controller
            Route::get('message/compose', 'MessageController@create');
            Route::get('message/outbox', 'MessageController@send_items');
            Route::get('message/inbox', 'MessageController@inbox_items');
            Route::get('message/outbox/{id}', 'MessageController@show_outbox');
            Route::get('message/inbox/{id}', 'MessageController@show_inbox');
            Route::post('message/send', 'MessageController@send');

            //SMS Controller
            Route::get('sms/compose', 'SmsController@create')->name('sms.compose');
            Route::get('sms/logs', 'SmsController@logs')->name('sms.view_logs');
            Route::post('sms/send', 'SmsController@send')->name('sms.compose');

            //Email Controller
            Route::get('email/compose', 'EmailController@create')->name('email.compose');
            Route::get('email/logs', 'EmailController@logs')->name('email.view_logs');
            Route::post('email/send', 'EmailController@send')->name('email.compose');

            //Notice Controller
            Route::get('notices/{id}', 'NoticeController@show')->where('id', '[0-9]+');
            Route::resource('notices', 'NoticeController');

            //Event Controller
            Route::get('events/{id}', 'EventController@show')->where('id', '[0-9]+');
            Route::resource('events', 'EventController');

            //Report Controller
            Route::match(['get', 'post'], 'reports/student_attendance_report/{view?}', 'ReportController@student_attendance_report')->name('reports.student_attendance_report');
            Route::match(['get', 'post'], 'reports/staff_attendance_report/{view?}', 'ReportController@staff_attendance_report')->name('reports.staff_attendance_report');
            Route::match(['get', 'post'], 'reports/student_id_card/{view?}', 'ReportController@student_id_card')->name('reports.student_id_card');
            Route::match(['get', 'post'], 'reports/exam_report/{view?}', 'ReportController@exam_report')->name('reports.exam_report');
            Route::match(['get', 'post'], 'reports/progress_card/{view?}', 'ReportController@progress_card')->name('reports.progress_card');
            Route::match(['get', 'post'], 'reports/class_routine/{view?}', 'ReportController@class_routine')->name('reports.class_routine');
            Route::match(['get', 'post'], 'reports/exam_routine/{view?}', 'ReportController@exam_routine')->name('reports.exam_routine');
            Route::match(['get', 'post'], 'reports/income_report/{view?}', 'ReportController@income_report')->name('reports.income_report');
            Route::match(['get', 'post'], 'reports/expense_report/{view?}', 'ReportController@expense_report')->name('reports.expense_report');
            Route::get('reports/account_balance', 'ReportController@account_balance')->name('reports.account_balance');

            //Permission Controller
            Route::get('permission/control/{role_id?}', 'PermissionController@index')->name('permission.manage');
            Route::post('permission/store', 'PermissionController@store')->name('permission.manage');


            //Role Controller
            Route::resource('permission_roles', 'RoleController');

            //CMS Controller
            Route::get('posts/type/{type?}', 'PostController@index')->name("posts.custom_post_list");
            Route::resource('posts', 'PostController');


            //Page Controller
            Route::resource('pages', 'PageController');

            //Post Categrory
            Route::get('post_categories/get_category', 'PostCategoryController@get_category');
            Route::resource('post_categories', 'PostCategoryController');

            //Route::get('website_languages/translate/{language_id?}','WebsiteLanguageController@translate')->name("website_languages.translate");
            //Route::post('website_languages/store_translate','WebsiteLanguageController@store_translate')->name("website_languages.translate");
            //Route::resource('website_languages','WebsiteLanguageController');

            //Site Navigation
            Route::resource('site_navigations', 'SiteNavigationController');
            Route::get('site_navigation_items/navigation/{navigation_id?}', 'NavigationItemController@index')->name("site_navigation_items.index");
            Route::get('site_navigation_items/create/{navigation_id?}', 'NavigationItemController@create')->name("site_navigation_items.create");
            Route::resource('site_navigation_items', 'NavigationItemController');

            Route::match(['get', 'post'], 'website/menu_sorting', 'FrontendSettingController@menu_sorting')->name('website.menu_sorting');
            Route::match(['get', 'post'], 'website/theme_option', 'FrontendSettingController@theme_option')->name('website.theme_option');

        });


        /** Teacher Route Group **/
        Route::group(['middleware' => ['teacher']], function () {
            Route::get('teacher/my_profile', 'Users\TeacherController@my_profile');
            Route::get('teacher/class_schedule', 'Users\TeacherController@class_schedule');
            Route::get('teacher/mark_register', 'Users\TeacherController@mark_register');
            Route::post('teacher/marks/create', 'Users\TeacherController@create_mark');
            Route::post('teacher/marks/store', 'Users\TeacherController@store_mark');
            Route::get('teacher/assignments', 'Users\TeacherController@assignments');
            Route::get('teacher/create_assignment', 'Users\TeacherController@create_assignment');
            Route::post('teacher/store_assignment', 'Users\TeacherController@store_assignment');
            Route::get('teacher/edit_assignment/{id}', 'Users\TeacherController@edit_assignment');
            Route::get('teacher/assignment/{id}', 'Users\TeacherController@show_assignment');
            Route::post('teacher/update_assignment/{id}', 'Users\TeacherController@update_assignment');
            Route::get('teacher/destroy_assignment/{id}', 'Users\TeacherController@destroy_assignment');
        });


        /** Student Route Group **/
        Route::group(['middleware' => ['student']], function () {
            Route::get('student/my_profile', 'Users\StudentController@my_profile');
            Route::get('student/my_subjects', 'Users\StudentController@my_subjects');
            Route::get('student/class_routine', 'Users\StudentController@class_routine');
            Route::match(['get', 'post'], 'student/exam_routine/{view?}', 'Users\StudentController@exam_routine');
            Route::get('student/progress_card', 'Users\StudentController@progress_card');
            Route::get('student/my_invoice/{status?}', 'Users\StudentController@my_invoice');
            Route::get('student/view_invoice/{id?}', 'Users\StudentController@view_invoice');
            Route::get('student/invoice_payment/{method?}/{invoice_id?}', 'Users\StudentController@invoice_payment');
            Route::get('student/paypal/{action?}/{invoice_id?}', 'Users\StudentController@paypal');
            Route::post('student/stripe_payment/{invoice_id?}', 'Users\StudentController@stripe_payment');
            Route::get('student/payment_history', 'Users\StudentController@payment_history');
            Route::get('student/library_history', 'Users\StudentController@library_history');
            Route::get('student/my_assignment', 'Users\StudentController@my_assignment');
            Route::get('student/view_assignment/{id?}', 'Users\StudentController@view_assignment');
            Route::get('student/my_syllabus', 'Users\StudentController@my_syllabus');
            Route::get('student/view_syllabus/{id?}', 'Users\StudentController@view_syllabus');
            Route::match(['get', 'post'], 'student/mark_chart/{subject_id?}', 'Users\StudentController@mark_chart');
        });


        /** Parent Route Group **/
        Route::group(['middleware' => ['parent']], function () {
            Route::get('parent/my_profile', 'Users\ParentController@my_profile');
            Route::get('parent/my_children/{student_id?}', 'Users\ParentController@my_children');
            Route::match(['get', 'post'], 'parent/children_attendance/{student_id?}', 'Users\ParentController@children_attendance');
            Route::get('parent/progress_card/{student_id?}', 'Users\ParentController@progress_card');
            Route::get('parent/payment_history/{student_id?}', 'Users\ParentController@payment_history');
            Route::get('parent/view_invoice/{id?}', 'Users\ParentController@view_invoice');
            Route::get('parent/invoice/{student_id?}', 'Users\ParentController@my_invoice');
            Route::match(['get', 'post'], 'parent/mark_chart/{student_id?}/{subject_id?}', 'Users\ParentController@mark_chart');
        });

    });

});

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::post('install/store_school', 'Install\InstallController@store_school');
Route::get('install/system_settings', 'Install\InstallController@system_settings');

Route::get('install/create_branch', 'Install\InstallController@create_branch');
Route::post('install/finish', 'Install\InstallController@final_touch');

Route::post('student/paypal_ipn', 'GatewayController@paypal_ipn');

app/SiteNavigation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SiteNavigation extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'site_navigations';
}

app/Http/Controllers/SiteNavigationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\SiteNavigation;
use Validator;
use Illuminate\Validation\Rule;

class SiteNavigationController extends Controller
{

	/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sitenavigations = SiteNavigation::all()->sortByDesc("id");
        return view('backend.cms.site_navigation.list',compact('sitenavigations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
		if( ! $request->ajax()){
		   return view('backend.cms.site_navigation.create');
		}else{
           return view('backend.cms.site_navigation.modal.create');
		}
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$validator = Validator::make($request->all(), [
			'menu_name' => 'required|max:191'
		]);

		if ($validator->fails()) {
			if($request->ajax()){
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect('site_navigations/create')
							->withErrors($validator)
							->withInput();
			}
		}



        $sitenavigation= new SiteNavigation();
	    $sitenavigation->menu_name = $request->input('menu_name');

        $sitenavigation->save();

		if(! $request->ajax()){
           return redirect('site_navigations/create')->with('success', ('Information has been added successfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'store','message'=>('Information has been added successfully'),'data'=>$sitenavigation]);
		}

   }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $sitenavigation = SiteNavigation::find($id);
		if(! $request->ajax()){
		   return view('backend.cms.site_navigation.edit',compact('sitenavigation','id'));
		}else{
           return view('backend.cms.site_navigation.modal.edit',compact('sitenavigation','id'));
		}

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$validator = Validator::make($request->all(), [
			'menu_name' => 'required|max:191'
		]);

		if ($validator->fails()) {
			if($request->ajax()){
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect()->route('site_navigations.edit', $id)
							->withErrors($validator)
							->withInput();
			}
		}



        $sitenavigation = SiteNavigation::find($id);
		$sitenavigation->menu_name = $request->input('menu_name');

        $sitenavigation->save();

		if(! $request->ajax()){
           return redirect('site_navigations')->with('success', ('Information has been updated successfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'update', 'message'=>('Information has been updated successfully'),'data'=>$sitenavigation]);
		}

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sitenavigation = SiteNavigation::find($id);
        $sitenavigation->delete();
        return redirect('site_navigations')->with('success',('Information has been deleted successfully'));
    }
}

resources/views/backend/cms/site_navigation/create.blade.php
@extends('layouts.backend')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">{{ ('Add Site Navigation') }}</div>

	<div class="panel-body">
	  <form method="post" class="validate" autocomplete="off" action="{{url('site_navigations')}}" enctype="multipart/form-data">
		{{ csrf_field() }}

		<div class="col-md-12">
		  <div class="form-group">
			<label class="control-label">{{ ('Menu Name') }}</label>
			<input type="text" class="form-control" name="menu_name" value="{{ old('menu_name') }}" required>
		  </div>
		</div>


		<div class="form-group">
		  <div class="col-md-12">
		    <button type="reset" class="btn btn-danger">{{ ('Reset') }}</button>
			<button type="submit" class="btn btn-primary">{{ ('Save') }}</button>
		  </div>
		</div>
	  </form>
	</div>
  </div>
 </div>
</div>
@endsection

resources/views/backend/cms/site_navigation/edit.blade.php
@extends('layouts.backend')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">{{ ('Update Site Navigation') }}</div>

			<div class="panel-body">
			<form method="post" class="validate" autocomplete="off" action="{{action('SiteNavigationController@update', $id)}}" enctype="multipart/form-data">
				{{ csrf_field()}}
				<input name="_method" type="hidden" value="PATCH">

				<div class="col-md-12">
				 <div class="form-group">
					<label class="control-label">{{ ('Menu Name') }}</label>
					<input type="text" class="form-control" name="menu_name" value="{{ $sitenavigation->menu_name }}" required>
				 </div>
				</div>


				<div class="form-group">
				  <div class="col-md-12">
					<button type="submit" class="btn btn-primary">{{ ('Update') }}</button>
				  </div>
				</div>
			</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/cms/site_navigation/list.blade.php
@extends('layouts.backend')

@section('content')

<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default no-export">
			<div class="panel-heading"><span class="panel-title">{{ ('Site Navigations') }}</span>
			<a class="btn btn-primary btn-sm pull-right ajax-modal" data-title="{{ ('Add Site Navigation') }}" href="{{route('site_navigations.create')}}">{{ ('Add New') }}</a>
			</div>

			<div class="panel-body">
			 @if (\Session::has('success'))
			  <div class="alert alert-success">
				<p>{{ \Session::get('success') }}</p>
			  </div>
			  <br />
			 @endif
			<table class="table table-bordered data-table">
			<thead>
			  <tr>
				<th>{{ ('Menu Name') }}</th>
				<th style="width:220px;">{{ ('Action') }}</th>
			  </tr>
			</thead>
			<tbody>

			  @foreach($sitenavigations as $sitenavigation)
			  <tr id="row_{{ $sitenavigation->id }}">
				<td class='menu_name'>{{ $sitenavigation->menu_name }}</td>
				<td>
				  <form action="{{ action('SiteNavigationController@destroy', $sitenavigation['id']) }}" method="post">
					<a href="{{ action('SiteNavigationController@edit', $sitenavigation['id']) }}" data-title="{{ ('Update Site Navigation') }}" class="btn btn-warning btn-sm ajax-modal">{{ ('Edit') }}</a>
					<a href="{{ url('site_navigation_items/navigation/'.$sitenavigation['id']) }}"  class="btn btn-info btn-sm">{{ ('Manage') }}</a>
					{{ csrf_field() }}
					<input name="_method" type="hidden" value="DELETE">
					<button class="btn btn-danger btn-sm btn-remove" type="submit">{{ ('Delete') }}</button>
				  </form>
				</td>
			  </tr>
			  @endforeach
			</tbody>
		  </table>
			</div>
		</div>
	</div>
</div>

@endsection