routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['install']], function () {
    //Auth Route
    Route::get('/login', function () {
        return redirect('login');
    });

    Auth::routes();

    //Frontend Route
    Route::get('/', 'WebsiteController@index');
    Route::get('/post/{slug?}', 'WebsiteController@single');
    Route::get('/category/{id?}', 'WebsiteController@category_archive');
    Route::get('/notice/{id?}', 'WebsiteController@notice');
    Route::get('/event/{id?}', 'WebsiteController@event');
    Route::post('/contact/send_message', 'WebsiteController@send_message');
    Route::get('/site/{slug?}', 'WebsiteController@index');


    Route::group(['middleware' => ['auth']], function () {
        /** Common Route for All **/
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        //Profile Controller
        Route::get('profile/my_profile', 'ProfileController@my_profile');
        Route::get('profile/edit', 'ProfileController@edit');
        Route::post('profile/update', 'ProfileController@update');
        Route::get('profile/changepassword', 'ProfileController@change_password');
        Route::post('profile/updatepassword', 'ProfileController@update_password');


        /** Permission Route Group **/
        Route::group(['middleware' => ['permission']], function () {

            //User Controller
            Route::get('users/get_users/{user_type}', 'UserController@get_users');
            Route::resource('users', 'UserController');

            //FrontOffice Route
            Route::get('frontoffice/{page?}', 'FrontOfficeController@index')->name('frontoffice.main_screen');
            Route::resource('admission_enquiries', 'AdmissionEnquiryController');
            Route::resource('visitor_informations', 'VisitorInformationController');
            Route::resource('phone_call_logs', 'PhoneCallLogController');
            Route::resource('complains', 'ComplainController');

            //Teacher Route
            Route::get('teachers/excel_import', 'TeacherController@excel_import')->name('teachers.excel_import');
            Route::post('teachers/excel_store', 'TeacherController@excel_store')->name('teachers.excel_import');
            Route::resource('teachers', 'TeacherController');
            Route::post('teachers/active/{id}', 'TeacherController@active')->name('teachers.active');
            Route::post('teachers/deactivate/{id}', 'TeacherController@deactivate')->name('teachers.deactivate');
            Route::get('teachers/certificate/{id}', 'TeacherController@certificate_create');
            Route::post('teachers/certificate_store', 'TeacherController@certificate_store');
            Route::get('teachers/nid/{id}', 'TeacherController@nid_create');
            Route::post('teachers/nid_store', 'TeacherController@nid_store');
            Route::get('teachers/certificate/view/{id}', 'TeacherController@certificate_view');
            Route::post('teachers/certificate_update/{id}', 'TeacherController@certificate_update');
            Route::match(['get', 'post'], 'teachers/certificate_remark/{id}', 'TeacherController@certificate_remark');

            //Parents Route
            Route::get('parents/get_parents', 'ParentController@get_parents');
            Route::get('parents/get_parents_list/{class_id}/{section_id}', 'ParentController@get_parents_list');
            Route::resource('parents', 'ParentController');
            Route::get('parents/nid/{id}', 'ParentController@nid_create');
            Route::post('parents/nid_store', 'ParentController@nid_store');

            //Student Route
            Route::get('students/excel_import', 'StudentController@excel_import')->name('students.excel_import');
            Route::post('students/excel_store', 'StudentController@excel_store')->name('students.excel_store');
            Route::get('students/id_card/{student_id}', 'StudentController@id_card')->name('students.view_id_card');
            Route::get('students/class/{class_id?}', 'StudentController@class')->name('students.index');
            Route::get('students/get_subjects/{class_id}', 'StudentController@get_subjects');
            Route::get('students/get_students/{class_id}/{section_id}', 'StudentController@get_students');
            Route::match(['get', 'post'], 'students/promote/{step?}', 'StudentController@promote')->name('students.promote');
            Route::resource('students', 'StudentController');
            Route::post('students/active/{id}', 'StudentController@active')->name('students.active');
            Route::post('students/deactivate/{id}', 'StudentController@deactivate')->name('students.deactivate');
            Route::post('students/certificate_remove/{id}', 'StudentController@certificate_remove');
            Route::get('students/certificate/{id}', 'StudentController@certificate_create');
            Route::post('students/certificate_store', 'StudentController@certificate_store');

            //Class Controller
            Route::resource('class', 'ClassController');
            Route::post('classes/class', 'ClassController@get_class');


            //Section Route
            Route::post('sections/section', 'SectionController@get_section');
            Route::get('sections/class/{class_id}', 'SectionController@index')->name('sections.index');
            Route::resource('sections', 'SectionController');

            //Subject Route
            Route::get('subjects/class/{class_id}', 'SubjectController@index')->name('subjects.index');
            Route::post('subjects/subject', 'SubjectController@get_subject');
            Route::resource('subjects', 'SubjectController');

            //Assign Subject Route
            Route::post('assignsubjects/search', 'AssignSubjectController@search')->name('assignsubjects.index');
            Route::resource('assignsubjects', 'AssignSubjectController');

            Route::resource('syllabus', 'SyllabusController');
            Route::get('syllabus/class/{class_id?}', 'SyllabusController@class');
            Route::resource('assignments', 'AssignmentController');
            Route::get('assignments/class/{class_id}', 'AssignmentController@class');
            Route::resource('academic_years', 'AcademicYearController');
            Route::get('branch_list/{id}', 'AcademicYearController@branch_list')->name('branch_list');
            Route::resource('branches', 'BranchController');
            Route::resource('student_groups', 'StudentGroupController');

            //Class Routine
            Route::get('class_routines', 'ClassRoutineController@index')->name('class_routines.index');
            Route::get('class_routines/class/{class_id}', 'ClassRoutineController@class')->name('class_routines.index');
            Route::get('class_routines/manage/{class_id}/{section_id}', 'ClassRoutineController@manage')->name('class_routines.edit');
            Route::post('class_routines/store', 'ClassRoutineController@store')->name('class_routines.create');
            Route::get('class_routines/show/{class_id}/{section_id}', 'ClassRoutineController@show')->name('class_routines.index');

            //Attendance Controller
            Route::match(['get', 'post'], 'student/attendance', 'AttendanceController@student_attendance')->name('student_attendance.create');
            Route::post('student/attendance/save', 'AttendanceController@student_attendance_save')->name('student_attendance.create');
            Route::match(['get', 'post'], 'staff/attendance', 'AttendanceController@staff_attendance')->name('staff_attendance.create');
            Route::post('staff/attendance/save', 'AttendanceController@staff_attendance_save')->name('staff_attendance.create');


            //Utility Controller
            Route::match(['get', 'post'], 'administration/general_settings/{store?}', 'UtilityController@settings')->name('general_settings.update');
            Route::post('administration/theme_option/{store?}', 'UtilityController@update_theme_option')->name('theme_option.update');
            Route::get('administration/change_session/{session_id}', 'UtilityController@change_session')->name('general_settings.update');
            Route::get('administration/change_branch/{branch_id}', 'UtilityController@change_branch');
            Route::post('administration/upload_logo', 'UtilityController@upload_logo')->name('general_settings.update');
            Route::get('administration/backup_database', 'UtilityController@backup_database')->name('utility.backup_database');

            //Language Controller
            Route::resource('languages', 'LanguageController');

            //PickList Controller
            Route::get('picklists/type/{type}', 'PicklistController@type')->name('picklists.index');
            Route::resource('picklists', 'PicklistController');

            //Library Controller
            Route::get('librarymembers/librarycard/{id}', 'LibraryMemberController@library_card')->name('librarymembers.view_library_card');
            Route::post('librarymembers/section', 'LibraryMemberController@get_section');
            Route::post('librarymembers/student', 'LibraryMemberController@get_student');
            Route::resource('librarymembers', 'LibraryMemberController');

            //Book Controller
            Route::resource('books', 'BookController');

            //Book Issue  Controller
            Route::match(['get', 'post'], 'bookissues/list/{library_id?}', 'BookIssueController@index')->name('bookissues.index');
            Route::get('bookissues/return/{id}', 'BookIssueController@book_return')->name('bookissues.return');

app/Complain.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Complain extends Model
{
    //
}

app/Http/Controllers/Branch_Admin/ComplainController.php
<?php

namespace App\Http\Controllers\Branch_Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Complain;

class ComplainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect('branch_admin_frontoffice/complains');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if( ! $request->ajax()){
            return view('backend.branch_admin.frontoffice.complains.create');
        }else{
            return view('backend.branch_admin.frontoffice.complains.modal.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'complain_type' => 'required|string|max:50',
            'source' => 'nullable|string|max:50',
            'complain_by' => 'required|string|max:100',
            'phone' => 'nullable|string|max:30',
            'email' => 'nullable|string|max:100',
            'taken_action' => 'nullable|string|max:250',
            'note' => 'nullable|string|max:250',
            'date' => 'required',
            'attach_document' => 'nullable|nullable|mimes:doc,pdf,docx,zip,png,jpg,jpeg',
        ]);

        if ($validator->fails()) {
            if($request->ajax()){
                return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
            }else{
                return redirect('branch_admin_complains/create')
                    ->withErrors($validator)
                    ->withInput();
            }
        }


        $complain = new Complain();
        $complain->session_id = get_session_year_option();
        $complain->complain_type = $request->complain_type;
        $complain->source = $request->source;
        $complain->complain_by = $request->complain_by;
        $complain->phone = $request->phone;
        $complain->email = $request->email;
        $complain->date = $request->date;
        $complain->taken_action = $request->taken_action;
        $complain->note = $request->note;
        $complain->branch_id = get_admin_branch_id();
        if($request->hasFile('attach_document')){
            $file = $request->file('attach_document');
            $file_name = time().rand(1,999).'.'.$file->getClientOriginalExtension();
            $file->move(base_path('public/uploads/files/complains/'),$file_name);
            $complain->attach_document = $file_name;
        }
        $complain->save();

        if(! $request->ajax()){
            return redirect('branch_admin_frontoffice/complains')->with('success', ('Information has been added sucessfully'));
        }else{
            return response()->json(['result'=>'success','action'=>'store_with_redirect','message'=>('Information has been added sucessfully'),'data'=>$complain]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $complain = Complain::find($id);
        if( ! $request->ajax()){
            return view('backend.branch_admin.frontoffice.complains.modal.show',compact('complain'));
        }else{
            return view('backend.branch_admin.frontoffice.complains.modal.show',compact('complain'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $complain = Complain::find($id);
        if( ! $request->ajax()){
            return view('backend.branch_admin.frontoffice.complains.edit',compact('complain'));
        }else{
            return view('backend.branch_admin.frontoffice.complains.modal.edit',compact('complain'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = \Validator::make($request->all(), [
            'complain_type' => 'required|string|max:50',
            'source' => 'nullable|string|max:50',
            'complain_by' => 'required|string|max:100',
            'phone' => 'nullable|string|max:30',
            'email' => 'nullable|string|max:100',
            'taken_action' => 'nullable|string|max:250',
            'note' => 'nullable|string|max:250',
            'date' => 'required',
            'attach_document' => 'nullable|nullable|mimes:doc,pdf,docx,zip,png,jpg,jpeg',
        ]);

        if ($validator->fails()) {
            if($request->ajax()){
                return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
            }else{
                return back()->withErrors($validator)->withInput();
            }
        }

        $complain = Complain::find($id);
        $complain->complain_type = $request->complain_type;
        $complain->source = $request->source;
        $complain->complain_by = $request->complain_by;
        $complain->phone = $request->phone;
        $complain->email = $request->email;
        $complain->date = $request->date;
        $complain->taken_action = $request->taken_action;
        $complain->note = $request->note;
        $complain->branch_id = get_admin_branch_id();

        if($request->hasFile('attach_document')){
            $file = $request->file('attach_document');
            $file_name = time().rand(1,999).'.'.$file->getClientOriginalExtension();
            $file->move(base_path('public/uploads/files/complains/'),$file_name);
            $complain->attach_document = $file_name;
        }
        $complain->save();

        if(! $request->ajax()){
            return redirect('branch_admin_frontoffice/complains')->with('success', ('Information has been updated sucessfully'));
        }else{
            return response()->json(['result'=>'success','action'=>'update_with_redirect','message'=>('Information has been updated sucessfully'),'data'=>$complain]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $complain = Complain::find($id);
        $complain->delete();
        return redirect('branch_admin_frontoffice/complains')->with('success', ('Information has been deleted'));
    }
}

resources/views/backend/frontoffice/complains/create.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="panel-title" >
					{{ ('Complain') }}
				</div>
			</div>
			<div class="panel-body">
				<form action="{{route('complains.store')}}" class="validate" autocomplete="off" enctype="multipart/form-data" method="post" accept-charset="utf-8">
					@csrf
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{ ('Complain Type') }} <a href="{{ url('picklists/create') }}" class="btn-link ajax-modal">{{ ('Add New') }}</a></label>
							<select class="form-control select2" name="complain_type" required>
								<option value="">{{ ('Select One') }}</option>
								{{ create_option("picklists","value","value",old('complain_type'),array("type="=>"Complain")) }}
							</select>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{ ('Source') }} <a href="{{ url('picklists/create') }}" class="btn-link ajax-modal">{{ ('Add New') }}</a></label>
							<select class="form-control select2" name="source" required>
								<option value="">{{ ('Select One') }}</option>
								{{ create_option("picklists","value","value",old('source'),array("type="=>"Source")) }}
							</select>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{ ('Complain By') }}</label>
							<input type="text" class="form-control" name="complain_by" value="{{ old('complain_by') }}" required>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{ ('Phone') }}</label>
							<input type="text" class="form-control" name="phone" value="{{ old('phone') }}">
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{ ('Email') }}</label>
							<input type="email" class="form-control" name="email" value="{{ old('email') }}">
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label">{{ ('Date') }}</label>
							<input type="text" class="form-control datepicker" name="date" value="{{ (old('date')) ? old('date') : Carbon\Carbon::now()->toDateString() }}" required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="control-label">{{ ('Branch') }}</label>
							<select name="branch" id="branch" class="form-control branch_select2" required>
								<option value="">Select One</option>
								{{ get_branch_list('branches','id','branch_name',old('branch')) }}
							</select>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="control-label">{{ ('Taken Action') }}</label>
							<textarea class="form-control" name="taken_action">{{ old('taken_action') }}</textarea>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="control-label">{{ ('Note') }}</label>
							<textarea class="form-control" name="note">{{ old('note') }}</textarea>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="control-label">{{('Attach Document')}}</label>
							<input type="file" class="form-control" name="attach_document">
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-12">
							<button type="submit" class="btn btn-info">{{ ('Save') }}</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/frontoffice/complains/edit.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="panel-title" >
					{{ ('edit') }}
				</div>
			</div>
			<div class="panel-body">
				<div class="col-md-8">
					<form method="post" autocomplete="off" action="{{ route('complains.update',$complain->id) }}" enctype="multipart/form-data">
						{{ csrf_field() }}
						@method('PUT')
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ ('Complain Type') }}</label>
								<select class="form-control select2" name="complain_type" required>
									<option value="">{{ ('Select One') }}</option>
									{{ create_option("picklists","value","value",$complain->complain_type,array("type="=>"Complain")) }}
								</select>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ ('Source') }}</label>
								<select class="form-control select2" name="source" required>
									<option value="">{{ ('Select One') }}</option>
									{{ create_option("picklists","value","value",$complain->source,array("type="=>"Source")) }}
								</select>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ ('Complain By') }}</label>
								<input type="text" class="form-control" name="complain_by" value="{{ $complain->complain_by }}" required>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ ('Phone') }}</label>
								<input type="text" class="form-control" name="phone" value="{{ $complain->phone }}">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ ('Email') }}</label>
								<input type="email" class="form-control" name="email" value="{{ $complain->email }}">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ ('Date') }}</label>
								<input type="text" class="form-control datepicker" name="date" value="{{ $complain->date }}" required>
							</div>
						</div>
						<div class="col-md-12">
							<div class=" form-group">
								<select class="form-control" name="branch">
									@foreach(get_branch('branches') as $branch)
										<option  value="{{ $branch->id }}" {{ $branch->id==get_branch_option('branch')  ? "selected" : "" }}>{{ ('Branch') }} ({{ $branch->branch_name }})</option>
									@endforeach
								</select>
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<label class="control-label">{{ ('Taken Action') }}</label>
								<textarea class="form-control" name="taken_action">{{ $complain->taken_action }}</textarea>
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<label class="control-label">{{ ('Note') }}</label>
								<textarea class="form-control" name="note">{{ $complain->note }}</textarea>
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<label class="control-label">{{('Attach Document')}}</label>
								<input type="file" class="form-control" name="attach_document">
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<button type="submit" class="btn btn-primary">{{ ('Update') }}</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/frontoffice/complains/show.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="panel-title" >
					{{('Profile')}}
				</div>
			</div>
			<div class="panel-body">
				<table class="table table-bordered" width="100%">
					<tbody style="text-align: center;">
						<tr class="text-center">
							<td colspan="2"><img src="{{ asset('public/uploads/images/profile.png') }}" style="width: 100px; border-radius: 5px"></td>
						</tr>
						<tr class="text-center">
							<td>{{ ('Complain Type') }}</td>
							<td>{{ $complain->complain_type }}</td>
						</tr>
						<tr class="text-center">
							<td>{{ ('Source') }}</td>
							<td>{{ $complain->source }}</td>
						</tr>
						<tr class="text-center">
							<td>{{ ('Complain By') }}</td>
							<td>{{ $complain->complain_by }}</td>
						</tr>
						<tr class="text-center">
							<td>{{ ('Phone') }}</td>
							<td>{{ $complain->phone }}</td>
						</tr>
						<tr class="text-center">
							<td>{{ ('Email') }}</td>
							<td>{{ $complain->email }}</td>
						</tr>
						<tr class="text-center">
							<td>{{ ('Date') }}</td>
							<td>{{ $complain->date }}</td>
						</tr>
						<tr class="text-center">
							<td>{{ ('Taken Action') }}</td>
							<td>{{ $complain->taken_action }}</td>
						</tr>
						<tr class="text-center">
							<td>{{ ('Note') }}</td>
							<td>{{ $complain->note }}</td>
						</tr>
						@if($complain->attach_document != '')
						<tr class="text-center">
							<td>{{ ('Attach Document') }}</td>
							<td><a href="{{ asset('public/uploads/files/complains/'.$complain->attach_document) }}"><i class="fa fa-download"></i></a></td>
						</tr>
						@endif
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection