routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['install']], function () {
    //Auth Route
    Route::get('/login', function () {
        return redirect('login');
    });

    Auth::routes();

    //Frontend Route
    Route::get('/', 'WebsiteController@index');
    Route::get('/post/{slug?}', 'WebsiteController@single');
    Route::get('/category/{id?}', 'WebsiteController@category_archive');
    Route::get('/notice/{id?}', 'WebsiteController@notice');
    Route::get('/event/{id?}', 'WebsiteController@event');
    Route::post('/contact/send_message', 'WebsiteController@send_message');
    Route::get('/site/{slug?}', 'WebsiteController@index');


    Route::group(['middleware' => ['auth']], function () {
        /** Common Route for All **/
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        //Profile Controller
        Route::get('profile/my_profile', 'ProfileController@my_profile');
        Route::get('profile/edit', 'ProfileController@edit');
        Route::post('profile/update', 'ProfileController@update');
        Route::get('profile/changepassword', 'ProfileController@change_password');
        Route::post('profile/updatepassword', 'ProfileController@update_password');


        /** Permission Route Group **/
        Route::group(['middleware' => ['permission']], function () {

            //User Controller
            Route::get('users/get_users/{user_type}', 'UserController@get_users');
            Route::resource('users', 'UserController');

            //FrontOffice Route
            Route::get('frontoffice/{page?}', 'FrontOfficeController@index')->name('frontoffice.main_screen');
            Route::resource('admission_enquiries', 'AdmissionEnquiryController');
            Route::resource('visitor_informations', 'VisitorInformationController');
            Route::resource('phone_call_logs', 'PhoneCallLogController');
            Route::resource('complains', 'ComplainController');

            //Teacher Route
            Route::get('teachers/excel_import', 'TeacherController@excel_import')->name('teachers.excel_import');
            Route::post('teachers/excel_store', 'TeacherController@excel_store')->name('teachers.excel_import');
            Route::resource('teachers', 'TeacherController');
            Route::post('teachers/active/{id}', 'TeacherController@active')->name('teachers.active');
            Route::post('teachers/deactivate/{id}', 'TeacherController@deactivate')->name('teachers.deactivate');
            Route::get('teachers/certificate/{id}', 'TeacherController@certificate_create');
            Route::post('teachers/certificate_store', 'TeacherController@certificate_store');
            Route::get('teachers/nid/{id}', 'TeacherController@nid_create');
            Route::post('teachers/nid_store', 'TeacherController@nid_store');
            Route::get('teachers/certificate/view/{id}', 'TeacherController@certificate_view');
            Route::post('teachers/certificate_update/{id}', 'TeacherController@certificate_update');
            Route::match(['get', 'post'], 'teachers/certificate_remark/{id}', 'TeacherController@certificate_remark');

            //Parents Route
            Route::get('parents/get_parents', 'ParentController@get_parents');
            Route::get('parents/get_parents_list/{class_id}/{section_id}', 'ParentController@get_parents_list');
            Route::resource('parents', 'ParentController');
            Route::get('parents/nid/{id}', 'ParentController@nid_create');
            Route::post('parents/nid_store', 'ParentController@nid_store');

            //Student Route
            Route::get('students/excel_import', 'StudentController@excel_import')->name('students.excel_import');
            Route::post('students/excel_store', 'StudentController@excel_store')->name('students.excel_store');
            Route::get('students/id_card/{student_id}', 'StudentController@id_card')->name('students.view_id_card');
            Route::get('students/class/{class_id?}', 'StudentController@class')->name('students.index');
            Route::get('students/get_subjects/{class_id}', 'StudentController@get_subjects');
            Route::get('students/get_students/{class_id}/{section_id}', 'StudentController@get_students');
            Route::match(['get', 'post'], 'students/promote/{step?}', 'StudentController@promote')->name('students.promote');
            Route::resource('students', 'StudentController');
            Route::post('students/active/{id}', 'StudentController@active')->name('students.active');
            Route::post('students/deactivate/{id}', 'StudentController@deactivate')->name('students.deactivate');
            Route::post('students/certificate_remove/{id}', 'StudentController@certificate_remove');
            Route::get('students/certificate/{id}', 'StudentController@certificate_create');
            Route::post('students/certificate_store', 'StudentController@certificate_store');

            //Class Controller
            Route::resource('class', 'ClassController');
            Route::post('classes/class', 'ClassController@get_class');


            //Section Route
            Route::post('sections/section', 'SectionController@get_section');
            Route::get('sections/class/{class_id}', 'SectionController@index')->name('sections.index');
            Route::resource('sections', 'SectionController');

            //Subject Route
            Route::get('subjects/class/{class_id}', 'SubjectController@index')->name('subjects.index');
            Route::post('subjects/subject', 'SubjectController@get_subject');
            Route::resource('subjects', 'SubjectController');

            //Assign Subject Route
            Route::post('assignsubjects/search', 'AssignSubjectController@search')->name('assignsubjects.index');
            Route::resource('assignsubjects', 'AssignSubjectController');

            Route::resource('syllabus', 'SyllabusController');
            Route::get('syllabus/class/{class_id?}', 'SyllabusController@class');
            Route::resource('assignments', 'AssignmentController');
            Route::get('assignments/class/{class_id}', 'AssignmentController@class');
            Route::resource('academic_years', 'AcademicYearController');
            Route::get('branch_list/{id}', 'AcademicYearController@branch_list')->name('branch_list');
            Route::resource('branches', 'BranchController');
            Route::resource('student_groups', 'StudentGroupController');

            //Class Routine
            Route::get('class_routines', 'ClassRoutineController@index')->name('class_routines.index');
            Route::get('class_routines/class/{class_id}', 'ClassRoutineController@class')->name('class_routines.index');
            Route::get('class_routines/manage/{class_id}/{section_id}', 'ClassRoutineController@manage')->name('class_routines.edit');
            Route::post('class_routines/store', 'ClassRoutineController@store')->name('class_routines.create');
            Route::get('class_routines/show/{class_id}/{section_id}', 'ClassRoutineController@show')->name('class_routines.index');

            //Attendance Controller
            Route::match(['get', 'post'], 'student/attendance', 'AttendanceController@student_attendance')->name('student_attendance.create');
            Route::post('student/attendance/save', 'AttendanceController@student_attendance_save')->name('student_attendance.create');
            Route::match(['get', 'post'], 'staff/attendance', 'AttendanceController@staff_attendance')->name('staff_attendance.create');
            Route::post('staff/attendance/save', 'AttendanceController@staff_attendance_save')->name('staff_attendance.create');


            //Utility Controller
            Route::match(['get', 'post'], 'administration/general_settings/{store?}', 'UtilityController@settings')->name('general_settings.update');
            Route::post('administration/theme_option/{store?}', 'UtilityController@update_theme_option')->name('theme_option.update');
            Route::get('administration/change_session/{session_id}', 'UtilityController@change_session')->name('general_settings.update');
            Route::get('administration/change_branch/{branch_id}', 'UtilityController@change_branch');
            Route::post('administration/upload_logo', 'UtilityController@upload_logo')->name('general_settings.update');
            Route::get('administration/backup_database', 'UtilityController@backup_database')->name('utility.backup_database');

            //Language Controller
            Route::resource('languages', 'LanguageController');

            //PickList Controller
            Route::get('picklists/type/{type}', 'PicklistController@type')->name('picklists.index');
            Route::resource('picklists', 'PicklistController');

            //Library Controller
            Route::get('librarymembers/librarycard/{id}', 'LibraryMemberController@library_card')->name('librarymembers.view_library_card');
            Route::post('librarymembers/section', 'LibraryMemberController@get_section');
            Route::post('librarymembers/student', 'LibraryMemberController@get_student');
            Route::resource('librarymembers', 'LibraryMemberController');

            //Book Controller
            Route::resource('books', 'BookController');

            //Book Issue  Controller
            Route::match(['get', 'post'], 'bookissues/list/{library_id?}', 'BookIssueController@index')->name('bookissues.index');
            Route::get('bookissues/return/{id}', 'BookIssueController@book_return')->name('bookissues.return');

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $table = 'teachers';
}

resources/views/backend/teachers/excel_import.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title" >
					{{('Import Excel')}}
				</div>
			</div>
			<div class="panel-body">
				<form method="post" action="{{url('teachers/excel_store')}}" enctype="multipart/form-data" class="validate">
					@csrf
					<div class="col-md-12">
						<div class="form-group">
							<label class="control-label">{{ ('File') }}</label>
							<input type="file" class="form-control appsvan-file" name="excel_file" required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<button type="submit" class="btn btn-primary rect-btn">{{ ('Import') }}</button>
						    <a href="{{ asset('public/excel/teachers_excel.xlsx') }}" class="btn btn-info pull-right rect-btn">{{ ('Download Excel File') }}</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/teachers/teacher-edit.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title" >
					{{ ('Update Teacher')}}
				</div>
			</div>
			<div class="panel-body">
			  <div class="col-md-8">
				<form action="{{route('teachers.update',$teacher->id)}}" autocomplete="off" class="form-horizontal validate" autocomplete="off" method="post" enctype="multipart/form-data">
					@csrf
					{{ method_field('PATCH') }}

					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Name')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="name" value="{{ $teacher->name }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Designation')}}</label>
						<div class="col-sm-9">
						    <select class="form-control select2" name="designation" required>
							   <option value="">{{  ('Select One') }}</option>
							   {{ create_option("picklists","value","value",$teacher->designation,array("type="=>"Designation")) }}
							</select>
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Birthday')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control datepicker_2" name="birthday" value="{{ $teacher->birthday }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Gender')}}</label>
						<div class="col-sm-9">
							<select name="gender" class="form-control select2" required>
								<option @if($teacher->gender=='Male') selected @endif value="Male">Male</option>
								<option @if($teacher->gender=='Female') selected @endif value="Female">Female</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Religion')}}</label>
						<div class="col-sm-9">
						    <select name="religion" class="form-control niceselect wide" required>
								<option value="">{{  ('Select One') }}</option>
								{{ create_option("picklists","value","value",$teacher->religion,array("type="=>"Religion")) }}
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Phone')}}</label>
						<div class="col-sm-9">
							<input type="number" class="form-control" name="phone" value="{{ $teacher->phone }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Address')}}</label>
						<div class="col-sm-9">
							<textarea class="form-control" name="address" required>{{ $teacher->address }}</textarea>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Joining Date')}}</label>
						<div class="col-sm-9">
							<input type="text" class="form-control datepicker" name="joining_date" value="{{ $teacher->joining_date }}" required>
						</div>
					</div>

					<hr>
					<div class="page-header">
					  <h4>Login Details</h4>
					</div>

					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Email')}}</label>
						<div class="col-sm-9">
							<input type="email" class="form-control" name="email" value="{{ $teacher->email }}" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Password')}}</label>
						<div class="col-sm-9">
							<input type="password" class="form-control" name="password">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Confirm Password')}}</label>
						<div class="col-sm-9">
							<input type="password" class="form-control" name="password_confirmation">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-3 control-label">{{ ('Profile Picture')}}</label>
						<div class="col-sm-9">
							<input type="file" class="form-control dropify" name="image" data-default-file="{{ asset('public/uploads/images/'.$teacher->image) }}" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG">
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-5">
							<button type="submit" class="btn btn-info">{{ ('Update Teacher')}}</button>
						</div>
					</div>
				</form>
			   </div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/backend/teachers/teacher-list.blade.php
@extends('layouts.backend')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="panel-title">Teachers List</span>

                    <a href="{{route('teachers.create')}}" class="btn btn-info btn-sm pull-right"
                       style="margin-left: 10px;">{{ ('Add New Teacher')}}</a>
                    <a href="{{url('teachers/excel_import')}}" class="btn btn-info btn-sm pull-right ajax-modal"
                       data-title="Import Excel">Import Excel</a>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered data-table">
                        <thead>
                        <th>Profile</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Designation</th>
                        <th>Active</th>
                        <th>Action</th>
                        </thead>
                        <tbody>
                        @foreach($teachers AS $data)
                            <tr>
                                <td><img class="img-circle" src="{{ asset('public/uploads/images/'.$data->image) }}" width="50px" alt="">
                                </td>
                                <td>{{$data->name}}</td>
                                <td>{{$data->email}}</td>
                                <td>{{$data->designation}}</td>
                                <td>
                                    @if ($data->status == 'Active')
                                        <form action="{{ route('teachers.deactivate',$data->id) }}" method="post">
                                            {{ method_field('POST') }}
                                            @csrf
                                            <button type="submit" class="btn btn-primary btn-xs btn-inactive"><i
                                                        class="fa fa-check" aria-hidden="true"></i></button>
                                        </form>
                                    @else
                                        <form action="{{ route('teachers.active',$data->id) }}" method="post">
                                            {{ method_field('POST') }}
                                            @csrf
                                            <button type="submit" class="btn btn-danger btn-xs btn-active"><i
                                                        class="fa fa-minus-circle" aria-hidden="true"></i></button>
                                        </form>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('teachers.show',$data->id)}}"
                                       class="btn btn-info btn-xs">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                    </a>
                                    <a href="{{route('teachers.edit',$data->id)}}" class="btn btn-warning btn-xs">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/teachers/teacher-view.blade.php
@extends('layouts.backend')
@section('content')
    <div class="row">
        <strong class="panel-title" style="display: none;">{{ ('Teacher Details') }}</strong>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="image">
                    <img src="{{ asset('public/uploads/images/background/background.jpg') }}" alt="...">
                </div>
                <div class="content">
                    <div class="author">
                        <img class="avatar border-white" src="{{ asset('public/uploads/images/'.$teacher->image) }}"
                             alt="{{ $teacher->name }}">
                        <h4 class="title">{{ $teacher->name }}</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <ul class="nav nav-tabs setting-tab">
                <li class="active">
                    <a data-toggle="tab" href="#profile" aria-expanded="true">{{ ('Profile') }}</a>
                </li>
                <li>
                    <a data-toggle="tab" href="#national_id" aria-expanded="false">{{ ('National ID') }}</a>
                </li>
                <li>
                    <a data-toggle="tab" href="#student_certificate" aria-expanded="false">{{ ('Certificate') }}</a>
                </li>
                <li class="pull-right">
                    <div style="padding: 7px;">
                        <a href="{{ url('teachers/certificate',$teacher->id) }}"
                           class="btn btn-primary rect-btn btn-sm"><i
                                    class="fa fa-upload" aria-hidden="true"></i>{{ ('Upload Certificate') }}</a>
                    </div>
                </li>
                <li class="pull-right">
                    <div style="padding: 7px;">
                        <a href="{{ route('teachers.edit',$teacher->id) }}" class="btn btn-primary rect-btn btn-sm"><i
                                    class="fa fa-pencil" aria-hidden="true"></i>{{ ('Edit') }}</a>
                    </div>
                </li>
            </ul>
            <div class="tab-content">
                <div id="profile" class="tab-pane fade in active">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <table class="table table-custom" width="100%">
                                <tbody>
                                <tr>
                                    <td>{{ ('Name') }}</td>
                                    <td>{{ $teacher->name }}</td>
                                </tr>
                                <tr>
                                    <td>{{ ('Designation') }}</td>
                                    <td>{{ ($teacher->designation) }}</td>
                                </tr>
                                <tr>
                                    <td>{{ ('Date Of Birth') }}</td>
                                    <td>{{ $teacher->birthday  }}</td>
                                </tr>
                                <tr>
                                    <td>{{ ('Gender') }}</td>
                                    <td>{{ $teacher->gender }}</td>
                                </tr>
                                <tr>
                                    <td>{{ ('Religion') }}</td>
                                    <td>{{ $teacher->religion }}</td>
                                </tr>
                                <tr>
                                    <td>{{ ('Joining Date') }}</td>
                                    <td>{{ $teacher->joining_date }}</td>
                                </tr>
                                <tr>
                                    <td>{{ ('Address') }}</td>
                                    <td>{{ $teacher->address }}</td>
                                </tr>
                                <tr>
                                    <td>{{ ('Phone') }}</td>
                                    <td>{{ $teacher->phone }}</td>
                                </tr>
                                <tr>
                                    <td>{{ ('Email') }}</td>
                                    <td>{{ $teacher->email }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div id="national_id" class="tab-pane fade">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @if(($teacher['nid_copy']) != NULL)
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        <table class="table table-custom" width="100%">
                                            <tbody>
                                            <tr>
                                                <td>National ID Card Number</td>
                                                <td>{{ $teacher->nid_number }}</td>
                                            </tr>
                                            <tr>
                                                <td>National ID Copy</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    @php
                                        $strExt = explode('.', $teacher->nid_copy);
                                    @endphp
                                    <div class="col-md-4">
                                        <div class="well well-sm">
                                            <div class="">

                                                    @if($strExt[1] === 'pdf')
                                                        <img style="height: 175px; width: 100%"
                                                             class="thumbnail img-responsive"
                                                             src="{{ asset('public/uploads/images/pdf.png') }}"/>
                                                    @else
                                                        <img style="height: 175px; width: 100%"
                                                             class="thumbnail img-responsive"
                                                             src="{{ asset('public/uploads/images/nid/'.$teacher->nid_copy) }}"/>
                                                    @endif
                                                    <a download class="btn btn-primary btn-xl"
                                                       href="{{ asset('public/uploads/images/nid/'.$teacher->nid_copy) }}">
                                                        <i class="fa fa-download"></i>
                                                    </a>
                                                    <a class="btn btn-info btn-xl" data-fancybox="filter"
                                                       data-caption="student_certificate" target="_blank"
                                                       href="{{ asset('public/uploads/images/nid/'.$teacher->nid_copy) }}">
                                                        <i class="fa fa-eye"></i>
                                                    </a>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12" style="margin-left: 10px;">
                                    <div style="padding: 7px;">
                                        <a href="{{ url('teachers/nid',$teacher->id) }}"
                                           class="btn btn-primary rect-btn btn-sm"><i
                                                    class="fa fa-upload" aria-hidden="true"></i>{{ ('Update NID') }}</a>
                                    </div>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
                <div id="student_certificate" class="tab-pane fade">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @foreach($certificates as $certificate)
                                @if(($certificate['certificate']) != NULL)
                                    @php
                                        $strExt = explode('.', $certificate->certificate);
                                    @endphp
                                    <div class="col-md-4">
                                        <div class="well well-sm">
                                            <div class="">
                                                @if($strExt[1] === 'pdf')
                                                    <img style="height: 175px; width: 100%"
                                                         class="thumbnail img-responsive"
                                                         src="{{ asset('public/uploads/images/pdf.png') }}"/>
                                                @else
                                                    <img style="height: 175px; width: 100%"
                                                         class="thumbnail img-responsive"
                                                         src="{{ asset('public/uploads/images/teacher_certificate/'.$certificate->certificate) }}"/>
                                                @endif
                                                    <a download class="btn btn-primary btn-xl"
                                                       href="{{ asset('public/uploads/images/teacher_certificate/'.$certificate->certificate) }}">
                                                        <i class="fa fa-download"></i>
                                                    </a>
                                                    <a class="btn btn-info btn-xl" data-fancybox="filter"
                                                       data-caption="student_certificate" target="_blank"
                                                       href="{{ asset('public/uploads/images/teacher_certificate/'.$certificate->certificate) }}">
                                                        <i class="fa fa-eye"></i>
                                                    </a>

                                                    <a href="{{ action('TeacherController@certificate_view',$certificate['id']) }}" class="btn btn-primary btn-xl">
                                                        <i class="fa fa-edit" aria-hidden="true"></i>
                                                    </a>

                                                    <a href="{{ action('TeacherController@certificate_remark',$certificate['id']) }}" data-title="Certificate Remark"  class="btn btn-info btn-xl ajax-modal">
                                                        <i class="fa fa-comments-o" aria-hidden="true"></i>
                                                    </a>

                                            </div>
                                        </div>
                                    </div>
                                @endif
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js-script')
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-fancybox="filter"]').fancybox({
                buttons: [
                    'slideShow',
                    'fullScreen',
                    'thumbs',
                    'download',
                    'zoom',
                    'close'
                ]
            });
        });
    </script>
@stop